env:
  browser: true
  es6: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:jest/recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - jest
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  no-unused-vars:
    - error
    - argsIgnorePattern: _
  react/no-string-refs:
    - off # TODO Fix
